test: continue on error

diff --git a/.github/workflows/testbot.yml b/.github/workflows/testbot.yml
--- a/.github/workflows/testbot.yml
+++ b/.github/workflows/testbot.yml
@@ -24,7 +24,8 @@ jobs:
         uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
 
       - name: Test with Gradle Wrapper
-        run: ./gradlew test --info
+        run: ./gradlew test --info || echo "Test failed, but continue..."
+        continue-on-error: true
 
       - name: Publish Test Results
         uses: EnricoMi/publish-unit-test-result-action@v2
